version: "3.9"

services:
  api-gateway-graphql:
    build: 
      context: api-gateway-graphql
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  grpc-service-auth:
    build:
      context: grpc-service-auth
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always

  grpc-service-cv:
    build:
      context: grpc-service-cv
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    restart: always
