version: "3.9"

services:
  api-gateway-graphql:
    build: ./api-gateway-graphql
    ports:
      - "3000:3000"
    restart: always

  grpc-service-auth:
    build: ./grpc-service-auth
    ports:
      - "3001:3001"
    restart: always

  grpc-service-cv:
    build: ./grpc-service-cv
    ports:
      - "3002:3002"
    restart: always
