version: '3'
services:
  api-gateway-graphql:
    build:
      context: ./api-gateway-graphql
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - './api-gateway-graphql:/usr/src/app'
    depends_on:
      - grpc-service-auth
      - grpc-service-cv
  grpc-service-auth:
    build:
      context: ./grpc-service-auth
      dockerfile: Dockerfile
    ports:
      - '50051:50051'
    volumes:
      - './grpc-service-auth:/usr/src/app'
  grpc-service-cv:
    build:
      context: ./grpc-service-cv
      dockerfile: Dockerfile
    ports:
      - '50052:50052'
    volumes:
      - './grpc-service-cv:/usr/src/app'
